; PlatformIO Project Configuration File
;
; TTGO T-Call (ESP32 + SIM800L) — Eitaa account creator
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
build_flags =
    -DCORE_DEBUG_LEVEL=0
